### ISSUE TITLE
Noetic support

### ISSUE THREAD

**Issue by ajinkyakhoche** [Kukanani/vision_msgs_visualization#4]
Hello. Thanks a lot for your wonderful work. When do you plan to provide support for ROS Noetic?

**Comment by Kukanani** [comment]
Hi, we already support Noetic: `sudo apt install ros-noetic-vision-msgs`

**Comment by Kukanani** [comment]
Ah, my mistake, this is on the visualization repo. Have you tried the source and had issues? Or are you asking for an apt release?

**Comment by ajinkyakhoche** [comment]
yes, i successfully built the package on Ubuntu 20.04 (ROS Noetic). I populated a Detection3DArray msg, but when i try to display it on Rviz, it crashes with message: Segmentation fault (core dumped). Other scripts work fine with Rviz

**Comment by Kukanani** [comment]
I was also able to build the package, but had no issues using it. I've pushed a new `noetic-devel` branch (and set it as the default branch, since Noetic is the latest LTS). If you continue to have issues, please post a minimal reproducible example and maybe I can help out. In the meantime, the original goal of the issue is satisfied so I am going to close. Thanks
